# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call(`_emDyNAM_timesTwo`, x)
}

getpDoAugment <- function(gammaEplus, gammaPlus, p, m, me, sender, receiver, typeA, indexSR, pAug) {
    .Call(`_emDyNAM_getpDoAugment`, gammaEplus, gammaPlus, p, m, me, sender, receiver, typeA, indexSR, pAug)
}

getpDoShort <- function(gammaEminus, gammaMinus, p, uniqueR, sender, receiver, typeS, pShort) {
    .Call(`_emDyNAM_getpDoShort`, gammaEminus, gammaMinus, p, uniqueR, sender, receiver, typeS, pShort)
}

getpDoPerm <- function(probVec, probVec2, e1, e2, sender1, receiver1, sender2, receiver2, me) {
    .Call(`_emDyNAM_getpDoPerm`, probVec, probVec2, e1, e2, sender1, receiver1, sender2, receiver2, me)
}

getKelMeMatrix <- function(seq, actDfnodesLab) {
    .Call(`_emDyNAM_getKelMeMatrix`, seq, actDfnodesLab)
}

getAuxDfE <- function(auxDf, sender, receiver) {
    .Call(`_emDyNAM_getAuxDfE`, auxDf, sender, receiver)
}

stepAugment <- function(seq, tieNames, gammaEplus, gammaPlus, m, me, net0, pAug) {
    .Call(`_emDyNAM_stepAugment`, seq, tieNames, gammaEplus, gammaPlus, m, me, net0, pAug)
}

stepShort <- function(seq, tieNames, gammaEminus, gammaMinus, m, me, Kel_g1, auxDf, pShort) {
    .Call(`_emDyNAM_stepShort`, seq, tieNames, gammaEminus, gammaMinus, m, me, Kel_g1, auxDf, pShort)
}

stepPerm <- function(seq, tieNames, m, me) {
    .Call(`_emDyNAM_stepPerm`, seq, tieNames, m, me)
}

