# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call(`_emDyNAM_timesTwo`, x)
}

subsetDataFrameTwoConditions <- function(df, columnName1, value1, columnName2, value2) {
    .Call(`_emDyNAM_subsetDataFrameTwoConditions`, df, columnName1, value1, columnName2, value2)
}

